#page title
page_title                                :                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 928863156                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://juliathemom.com               # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Nappy Pin – Breastfeeding Log                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Old-school moms used to attach a nappy pin to their bra so they could remember which breast was due to use next. For modern moms there is an app for that.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Alexey Plekhanov                                
your_link                                 : mailto:mail@aplekhanov.com
your_city                                 :                                 
email_address                             :
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          :
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Focus on important
    description                           : Clean and simple to use interface designed for one-hand operation. Just tap a button to get started and focus on your baby.
    fontawesome_icon_name                 : eye
    
  - title                                 : Complete feeding history
    description                           : Nappy Pin keeps all your baby's feed times in clear journal. It shows how long you have fed your baby, including time between feeds.
    fontawesome_icon_name                 : list

  - title                                 : Respectful of Privacy
    description                           : Personalize the app to your baby by adding a picture, baby’s name, and date of birth. No ads, no registrations, and no login screens. All your data is local and private. Just you, your baby, and a nice little app.
    fontawesome_icon_name                 : shield-alt



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#b36800"
cover_overlay_transparency                : 0.8

device_color                              : coral                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#FF9500"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#333333"

feature_icons_foreground_color            : "#FF9500"
feature_icons_background_color            : "#00FF95"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
